
import { BrowserRouter, Link, Route, Routes } from 'react-router-dom';
import { logov2 } from '../assets';
import React, { useEffect, useState } from 'react';
import { Card, FormField, Loader } from '../components';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post._id} {...post} />)
    );
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState(null);

  const fetchPosts = async () => {
    setLoading(true);

    try {
      const response = await fetch("http://localhost:7070/api/v1/post", {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const result = await response.json();
        setAllPosts(result.data.reverse());
      }
    } catch (err) {
      alert(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
        setSearchedResults(searchResult);
      }, 500),
    );
  };
  
  return (
    <section className="max-w-7xl mx-auto">

      <div className="my-10 cols-container flex">
        <div className="xs:w-6-cols md:w-4-cols lg:w-6-cols ">
        <h1 className="f-display-2 font-extrabold text-[#222328] text-[48px]">IMAGINEFY: Extending creativity</h1>
        <div className="mt-spacing-4 f-subhead-1 ui-richtext">
          <div className="max-w-xl text-[24px] my-6">
          <p>As part of our IMAGINEFY research preview, more than 3,000 artists from more than 118 countries have incorporated IMAGINEFY into their creative workflows. The artists in our early access group have helped us discover new uses for IMAGINEFY and have served as key voices as we’ve made decisions about IMAGINEFY</p>
          </div>
        </div>
        <div className="py-8"><Link to="/create-post" className="mt-2 font-inter font-medium bg-[#00ADE1] text-[18px] text-white px-12 py-6 rounded-full">Create your art 🎨</Link></div>
        </div>
        
        <div className="xs:w-6-cols xs:mt-72 md:w-4-cols md:mt-0 lg:w-6-cols">
          <figure className="text-right rounded-lg">
            <div className="ratio ratio-1x1 rounded-lg">
              <img className=" rounded-lg" src="https://images.openai.com/blob/6aec296d-b9b9-4f4e-93a0-216717ec533b/dall-e-2-extending-creativity.jpg?trim=0,0,0,0&width=2000" width="720" height="720" alt="A colorful silhouette of a woman with long, flowing hair, generated by Imaginefy"/>
            </div>
          </figure>
        </div>
      </div>
      
      <div className="pt-6">
        <h1 className="font-extrabold text-[#222328] text-[40px] flex justify-center">The Community Showcase</h1>
        <p className="mt-2 text-[#808080] text-[18px] flex justify-center">Browse through a collection of imaginative and visually stunning images generated by IMAGINEFY</p>
        
      </div>

  
        

      <div className="mt-8 " >
        <FormField
          labelName=""
          type="text"
          name="text"
          placeholder="Search in community..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Resuls for <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No Posts Yet"
                />
              )}
            </div>
          </>
        )}
      </div>

      <footer className="relative bg-blueGray-200 pt-8 pb-6">
        <div className="container rounded-lg bg-[#353935] mx-auto px-4 pt-8 ">
          <div className="flex flex-wrap text-left lg:text-left">
            <div className="w-full px-4">
            <Link to="/">
              <img src={logov2} alt="logo" className="w-50 object-contain py-8" />
              </Link>
              <div className="w-full flex justify-between ">
                <div>
                <h5 className="text-lg text-[white] lg:w-8/12 mt-0 mb-2 text-[24px] ">Our hope is that Imaginefy will empower people to express themselves creatively. Imaginefy also helps us understand how advanced AI systems see and understand our world, which is critical to our mission of creating AI that benefits humanity.</h5>
              
                </div>
                
                  <div className="w-full lg:w-6/12 text-[white] px-4">
              <div className="flex flex-wrap items-top mb-6">
                <div className="w-full lg:w-8/12 px-4 ml-auto ">
                  <span class="block uppercase text-[18] font-normal mb-2">Useful Links</span>
                  <ul className="list-unstyle">
                    <li><a class="hover:text-[#00ADE1] transition delay-150 font-inter font-normal block pb-2 text-[18px]" href="/report">Report</a></li>
                    <li><a class="hover:text-[#00ADE1] transition delay-150  font-normal block pb-2 text-[18px]" href="https://github.com/Harsh1804/ai_image">Github</a></li>
                    <li><a class="hover:text-[#00ADE1] transition delay-150  font-normal block pb-2 text-[18px]" href="/aboutus">About us</a></li>
                  </ul>
                

              </div>
            </div>
            </div>
              </div>
              
            </div>
            
          </div>
          <hr class="my-6 border-blueGray-300"></hr>
          <div className="flex flex-wrap  items-center md:justify-between justify-center">
              <div className="w-full md:w-4/12 px-4 mx-auto text-[white] text-center">
                <div className="text-sm mb-8 text-blueGray-500 font-semibold py-1">
                Copyright © <span id="get-current-year">2023</span><a href="" class="hover:text-[#00ADE1] transition delay-150" > Imaginefy </a>
                <a class=""> by Harsh & Jay</a>
                </div>
              </div>
          </div>

        </div>
      </footer>

    </section>
  );
  <main className="sm:p-8 px-4 py-8 w-full bg-[#f9fafe] min-h-[calc(100vh-73px)]">
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/create-post" element={<CreatePost />} />
        <Route path="/aboutus" element={<Aboutus />} />
      </Routes>
    </main>
};

export default Home;
